### ISSUE TITLE
Add Heroku Deploy Button 

### ISSUE THREAD

**Issue by besoeasy** [WinPooh32/Go-PeersToHTTP#2]
hey it will be nice to have heroku deploy button, so we can test application using your preferred parameters

**Comment by WinPooh32** [comment]
It's impossible for now due to some dependency [issue](https://github.com/anacrolix/torrent/issues/312)

**Comment by pataquets** [comment]
For the record, Heroku forbids torrent software on his platform's AUP. It happened to me some time ago while trying similar software.
cc: @WinPooh32
